apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: minikube-pool
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 0s
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
      nodeClassRef:
        name: hsarch-test
        kind: EC2NodeClass
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: minikube-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: {}
