apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: minikube-pool
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 0s
  template:
    spec:
      nodeClassRef:
        name: minikube-demo
        group: karpenter.k8s.aws
        kind: EC2NodeClass
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
